- name: standard
  display_name: Standard
  elements: [article, claim, header, bild, bild_text, text, headline, intro, image_mosaic]
  autogenerate: [header, claim, article]

- name: contact
  display_name: Kontakt
  unique: true
  cache: false
  elements: [headline, text, contactform]
  autogenerate: [headline, text, contactform]

- name: news
  display_name: News
  feed: true
  elements: [headline, news]
  autogenerate: [news]

- name: search
  display_name: Suche
  unique: true
  cache: false
  elements: [headline, text, searchresult]
  autogenerate: [searchresult]

- name: layout_header
  display_name: Layout Header
  unique: true
  hide: true
  elements: [sitename]

- name: layout_footer
  display_name: Layout Footer
  unique: true
  hide: true
  elements: [footnote]
    
- name: newsletter_layout
  display_name: Newsletter
  unique: false
  newsletter: true
  elements: [newsletter_article, newsletter_intro]

- name: external
  display_name: Externe Seite
  redirects_to_external: true
