language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx-19mode
branches:
  only:
    - 2.2-stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sh -c 'cd spec/dummy && RAILS_ENV=test bundle exec rake db:create db:schema:load --trace'"
script: "bundle exec rspec spec --format=doc"
env:
  - DB=mysql
  - DB=postgresql
matrix:
  allow_failures:
    - rvm: rbx-19mode
