sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %><%= ENV['TEST_ENV_NUMBER'] %>.sqlite3

mysql: &mysql
  adapter: mysql2
  encoding: utf8mb4
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: alchemy_cms_dummy_<%= Rails.env %><%= ENV['TEST_ENV_NUMBER'] %>

mariadb: &mariadb
  adapter: mysql2
  encoding: utf8mb4
  port: 3307
  username: root
  database: alchemy_cms_dummy_<%= Rails.env %><%= ENV['TEST_ENV_NUMBER'] %>

postgresql: &postgresql
  adapter: postgresql
  <% if ENV['DB_USER'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  <% end %>
  database: alchemy_cms_dummy_<%= Rails.env %><%= ENV['TEST_ENV_NUMBER'] %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  <% if ENV['DB_HOST'] %>
  host: <%= ENV['DB_HOST'] %>
  <% end %>
  <<: *<%= ENV['DB'] || "sqlite" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
