development:
  adapter: mysql
  encoding: utf8
  database: alchemy_dev
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: alchemy_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  database: alchemy_dev
  username: root
  password:
  socket: /tmp/mysql.sock
