- name: index
  unique: true

- name: standard
  elements: [article, header, slider]
  autogenerate: [header, article]

- name: everything
  cells: [right_column]
  elements: [text, all_you_can_eat]
  autogenerate: [all_you_can_eat]

- name: news
  feed: true
  unique: true
  insert_elements_at: top
  elements: [headline, news]
  autogenerate: [news]
  feed_elements: [news]

- name: contact
  unique: true
  cache: false
  elements: [headline, text, contactform]
  autogenerate: [headline, text, contactform]

- name: external
  unique: false
  redirects_to_external: true

- name: <%= 'erb_' + 'layout' %>
  unique: true
